// FixedPositions // Don't change so we can have backward compatibility

// If identifier read at position 0 matches ARCHITECTURE_IDENTIFIER, then the file was writting from
// native architecture
#define SONATA_REPORT_ARCHITECTURE_IDENTIFIER 1.001

// Double:
#define SONATA_REPORT_IDENTIFIER_POSITION 0
// Int:
#define SONATA_REPORT_HEADER_SIZE_POSITION SONATA_REPORT_IDENTIFIER_POSITION + sizeof(double)
// String:
#define SONATA_REPORT_LIBRARY_VERSION_POSITION 16
// String:
#define SONATA_REPORT_SIMULATOR_VERSION_POSITION 32
// Int:
#define SONATA_REPORT_TOTAL_NUMBER_OF_CELLS_POSITION 48
// Int:
#define SONATA_REPORT_TOTAL_NUMBER_OF_COMPARTMENTS_POSITION 52
// Int:
#define SONATA_REPORT_NUMBER_OF_STEPS_POSITION 64
// Double:
#define SONATA_REPORT_TIME_START_POSITION 72
// Double:
#define SONATA_REPORT_TIME_END_POSITION 80
// Double:
#define SONATA_REPORT_DT_TIME_POSITION 88
// String:
#define SONATA_REPORT_D_UNIT_POSITION 96
// String:
#define SONATA_REPORT_T_UNIT_POSITION 112
// Int:
#define SONATA_REPORT_MAPPING_SIZE_POSITION 128
// String:
#define SONATA_REPORT_MAPPING_NAME_POSITION 144
// Int:
#define SONATA_REPORT_EXTRA_MAPPING_SIZE_POSITION 160
// String:
#define SONATA_REPORT_EXTRA_MAPPING_NAME_POSITION 176
// String:
#define SONATA_REPORT_TARGET_NAME_POSITION 192

// Length definition
// int:
#define SONATA_REPORT_HEADER_LENGTH 1024
// int:
#define SONATA_REPORT_SIZE_CELL_INFO_LENGTH 64
// int:
#define SONATA_REPORT_SIZE_STRING 16

// Inside CellInfo
// Int:
#define SONATA_REPORT_NUMBER_OF_CELL_POSITION 0
// Int:
#define SONATA_REPORT_NUMBER_OF_COMPARTMENTS_POSITION 8
// OffSet:
#define SONATA_REPORT_DATA_INFO_POSITION 16
// OffSet:
#define SONATA_REPORT_EXTRA_MAPPING_INFO_POSITION 24
// OffSet:
#define SONATA_REPORT_MAPPING_INFO_POSITION 32

// order of the cell is a simple string order
